AnBoIms/AnBoIms

- logs/1031업무일지.md
> sj small conflict

- logs/1101업무일지.md
> plan modify

- logs/1101업무일지.md
> sj1101 issue Try

- logs/1101업무일지.md
> add hj's log

- logs/1104업무일지.md
> sj 1104 diary

- logs/1105업무일지.md
> sj1105 diary update

- logs/1105업무일지.md
> log modify

- logs/1106업무일지.md
> add hj's 1106 log

- logs/1106업무일지.md
> sj 1106 diary update

- logs/1107업무일지.md
> sj1107 diary

- logs/1107업무일지.md
> wjhmodifylog

- logs/1108업무일지.md
> add hj's 1108 log

- logs/1108업무일지.md
> sj1108 log update

- logs/1108업무일지.md
> wjhlog-modify

- logs/1111업무일지.md
> sj1111 log update:

- logs/1111업무일지.md
> wjhlogmodify

- logs/1111업무일지.md
> add hj's 1111 log

- logs/1112업무일지.md
> 1112 log sj update

- logs/1113업무일지.md
> sj1113 log update

- logs/1118업무일지.md
> sj 1118 log update

- logs/1112업무일지.md
- logs/1113업무일지.md
- logs/1118업무일지.md
> add hj's 1118log

- logs/1119업무일지.md
> add hj's 1119 log

- logs/1119업무일지.md
> wjh_log_modify

- logs/1119업무일지.md
> sj1119 log update

- logs/1119업무일지.md
- logs/1120업무일지.md
> sj 1120 log update

- TIDC/readme.md
> sjh.readme

- logs/1121업무일지.md
> add hj's 1121 log

- mmdetection/README_anboims.md
modify mmdetection README_anboims.md
> readme-modify

- logs/1122업무일지.md
> add hj's 1122 log

- mmdetection/README_anboims.md
modify mmdetection/README_anboims.md
> readme_anboims

- CRAFT+Perspective/test.py
- logs/1126업무일지.md
> sj 1126 log update

- logs/1127업무일지.md
> sj1127 log update

- logs/1126업무일지.md
- logs/1127업무일지.md
> add hj's 1127 log

- mmdetection/README_anboims.md
- mmdetection/idcard_output.py
mmdetection README_anboims.md 파일 업데이트
> mmdetection-readme-modify

- logs/1128업무일지.md
> add hj's 1128 log

- mmdetection/README_anboims.md
> readme_file_modify_mm

- logs/1129업무일지.md
> sj 1129 log update

- EasyOCR/category_classification.py
> add EasyOcr idcard_category classification v0.0.2

- TIDC/TIDC.py
- TIDC/create.py
- TIDC/readme.md
> TIDC_update/sjh

- logs/1203업무일지.md
> sj1203 log update

- logs/1204업무일지템.md
> sj1204 log update

- logs/1204업무일지템.md
> log-modify

- TIDC/TIDC.py
- TIDC/create.py
- TIDC/readme.md
> TIDC update/sjh

- TIDC/TIDC.py
- TIDC/readme.md
> TIDC_last(hope)/sjh

- logs/1206업무일지.md
> add hj's 1206 log

- logs/1206업무일지.md
> sj1206 log update

- logs/1209업무일지.md
- logs/1210업무일지.md
> sj 1210 log update

- logs/1209업무일지.md
- logs/1210업무일지.md
> add hj's 1209, 1210 log
